### ISSUE TITLE
File export (OneDrive, SharePoint, Teams)

### ISSUE THREAD

**Issue by gmatev** [alcionai/corso-roadmap#43]
Instead of restoring back to service, download content.

- Individual file in the format that exists - P0
- Multiple files as a ZIP - P1

This capability will originally apply to all services supported at time of introducing the capability. Once the workflow is supported, it will need to be supported when adding new services or service content types.

**Comment by meain** [comment]
@gmatev Do we have to provide zip as a option for exporting multiple files in the cli? How about we just recreate the folder hierarchy on user's filesystem(restore the data as is to users filesystem). We can provide it in such a way that any SDK consumer can generate a zip file from the data instead of writing to the filesystem.

This has two advantages, we are not tied to any specific format nor do we have to implement different archival formats in future in the core.

**Comment by gmatev** [comment]
I get what you are saying but I do think that it makes is more challenging for SDK consumers to perform the desired task. As for the. formats, I think zip should be well covered in the M365 ecosystem. Also, we can make this step optional (flag to disable it). Consumers can them do other formats if zip is not sufficient although I doubt that.

**Comment by meain** [comment]
Makes sense, I guess we'll add an option to let them either get a list of files and folders or a single entity(file data in case single file or zip in case of multiple files).
